"""
sustech_survival.context.profile — fill the user's personal profile.

The skills ship with a BLANK profile; on first install the agent:

  1. installs/imports ``sustech_survival``,
  2. asks the user for SUSTech SSO credentials (or points them to
     ``credentials.txt`` in the documented format ``sid:password``),
  3. runs :func:`gen_usr_profile` to query TIS/BB and render a filled
     Markdown profile to a path the agent picks (e.g. ``~/sustech_profile.md``).

A blank Markdown template lives at ``templates/profile.md`` in this package
so the skill can ship/copy it verbatim. The template uses ``{{field}}``
placeholders that :func:`gen_usr_profile` substitutes.

Every network call is guarded — a missing field never crashes profile
generation; it renders ``(unknown)`` and moves on.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

# -- Blank template (also shipped as templates/profile.md) --------------------

_BLANK_MD = """\
# SUSTech Student Profile

> Auto-generated by ``sustech_survival.context.profile``. Edit freely; this is
> the agent's workspace copy, not a config source.

## Identity
- **SID**     : {{sid}}
- **Name**    : {{name}}
- **Department** : {{department}}  ({{dept_code}})
- **Enrollment** : {{class_name}}
- **Year/track** : {{major}} ({{level}}, track={{track}})
- **Phone**   : {{phone}}

## Academic
- **Current term**   : {{current_semester}}
- **Enrolled courses**: {{course_count}}
- **Next exam**       : {{next_exam}}
- **Next BB deadline**: {{next_deadline}}

## Account
- **TIS user code**   : {{user_code}}
- **Email**           : {{email}}

---
_generated {{generated_at}}_
"""


# -- Session + discovery helpers (all guarded) --------------------------------

def _tis_auth():
    """Ensure a working TIS session, or raise a helpful error."""
    from sustech_survival.sso import TISAuth
    auth = TISAuth()
    ok, reason = auth.ensure()
    if not ok:
        raise RuntimeError(
            "Could not authenticate to TIS — make sure credentials.txt has "
            f"the SUSTech SSO credentials. Reason: {reason}"
        )
    return auth


def _get_json(auth, url: str, *, post_data: Optional[dict] = None) -> dict:
    """GET/POST a TIS endpoint and return JSON, or {} on any failure."""
    try:
        if post_data is not None:
            r = auth.post(url, data=post_data, timeout=10)
        else:
            r = auth.get(url, timeout=10)
        if r.status_code != 200:
            return {}
        return r.json() or {}
    except Exception:
        return {}


def _scalar(d: dict, *keys: str) -> str:
    """Return the first present non-empty scalar value among ``keys``."""
    for k in keys:
        v = d.get(k)
        if v not in (None, "", [], {}):
            return str(v)
    return ""


# -- Core fetch: build a profile dict ----------------------------------------

def fetch_profile(*, semester=None) -> dict[str, Any]:
    """Query TIS for the current user's identity + academic snapshot.

    Returns a dict with keys matching the profile template placeholders.
    Every field defaults to "(unknown)" rather than raising.
    """
    from datetime import datetime
    from sustech_survival.semester import Semester

    auth = _tis_auth()
    sem = semester if semester is not None else Semester.current()

    me = _get_json(auth, "/user/me")
    # TIS /user/me field mapping (verified 2026-09 against the live endpoint):
    #   yhdm      → TIS user code (numeric SID)
    #   xm        → Chinese name
    #   xm_en     → English name
    #   bmdm      → department code (e.g. "020020")
    #   bmmc      → department name (e.g. "材料科学与工程系")
    #   bmmc_en   → department name EN
    #   pyccm     → 培养层次码 (e.g. "03" = 本科, "02" = 硕士)
    #   pylx      → 培养类型 (e.g. "1")
    #   lxdh      → phone (mobile)
    # Major (zymc) and email (dzz_em) are NOT returned by /user/me — they
    # live on a different endpoint or have to be inferred from the class
    # roster. Kept as (unknown) with a TODO until we find the right call.
    _PYCCM_TO_LEVEL = {
        "01": "专科",
        "02": "硕士",
        "03": "本科",
        "04": "博士",
    }
    pyccm_code = (me.get("pyccm") or "").strip()
    pyccm_label = _PYCCM_TO_LEVEL.get(pyccm_code, pyccm_code)

    profile = {
        "sid": _scalar(me, "sid", "yhdm", "xh") or "(unknown)",
        "name": _scalar(me, "xm", "name", "trueName") or "(unknown)",
        "department": _scalar(me, "bmmc", "department", "ssmc", "szmc", "deptName") or "(unknown)",
        "class_name": _scalar(me, "ssmc", "bj", "className", "szbj") or "(unknown)",
        "major": _scalar(me, "zymc", "major", "zy") or "(unknown)",
        "user_code": _scalar(me, "yhdm", "sid") or "(unknown)",
        "email": _scalar(me, "email", "dzz_em") or "(unknown)",
        # New fields: phone + 培养层次 + 培养类型
        "phone": _scalar(me, "lxdh", "mobile", "phone") or "(unknown)",
        "level": pyccm_label or "(unknown)",
        "track": _scalar(me, "pylx") or "(unknown)",
        "dept_code": _scalar(me, "bmdm") or "(unknown)",
    }

    # Enrolled courses for the current term — TIS schedule endpoint.
    course_count = 0
    try:
        sched = _get_json(
            auth,
            "/xszykb/queryxszykbzong",
            post_data={"xn": sem.xn, "xq": sem.xq},
        )
        rows = sched.get("content") or sched.get("list") or sched.get("rows") or []
        if isinstance(rows, list):
            course_count = len(rows)
        else:
            # Some TIS versions key course rows by an explicit count field.
            course_count = int(sched.get("total", 0) or 0)
    except Exception:
        course_count = 0

    profile["current_semester"] = str(sem)
    profile["course_count"] = str(course_count)

    # Next exam / deadline (best-effort, non-fatal).
    from sustech_survival.context import fetch_next_exam, fetch_next_deadline
    try:
        nex = fetch_next_exam() or {}
        profile["next_exam"] = nex.get("text") or nex.get("name") or nex.get("due") or "(none)"
    except Exception:
        profile["next_exam"] = "(unknown)"
    try:
        ndl = fetch_next_deadline() or {}
        profile["next_deadline"] = ndl.get("text") or ndl.get("name") or ndl.get("due") or "(none)"
    except Exception:
        profile["next_deadline"] = "(unknown)"

    profile["generated_at"] = datetime.now().strftime("%Y-%m-%d %H:%M")
    return profile


# -- Renders the filled profile to a path ------------------------------------

def gen_usr_profile(path: Optional[str] = None, *, template: Optional[str] = None) -> str:
    """Generate the user's filled profile Markdown and write it to ``path``.

    Args:
        path: where to write the profile. Defaults to ``./sustech_profile.md``.
        template: an optional Jinja-less format string with ``{{field}}``
            placeholders. Defaults to the bundled blank template.

    Returns:
        The path the profile was written to.

    The flow (per the skill contract):
        1. the agent has ensured credentials.txt holds ``sid:password``,
        2. this calls :func:`fetch_profile` (authenticates to TIS),
        3. renders the template, writing it to ``path``.
    """
    from datetime import datetime

    values = fetch_profile()
    values.setdefault("generated_at", datetime.now().strftime("%Y-%m-%d %H:%M"))

    tpl = template
    if tpl is None:
        # Try the packaged template; fall back to the inline blank.
        bundled = Path(__file__).resolve().parent / "templates" / "profile.md"
        if bundled.exists():
            tpl = bundled.read_text(encoding="utf-8")
        else:
            tpl = _BLANK_MD

    rendered = tpl
    for key, val in values.items():
        rendered = rendered.replace("{{" + key + "}}", str(val))
    # Any placeholder left unfilled → (unknown)
    import re
    rendered = re.sub(r"\{\{[a-zA-Z0-9_]+\}\}", "(unknown)", rendered)

    # Default write path: the user's config dot-directory, NOT cwd. Writing
    # PII (SID + name) to whatever directory the agent happens to be in is a
    # footgun — it silently drops a profile.md next to any project the user is
    # working in. We use ``config_root()`` so we respect the same $SUSTECH_HOME
    # override the rest of the package honours (and avoid the iron-law #12
    # ban on raw ``Path.home()`` access outside sso/authorizer.py).
    # Users can still pass an explicit --output to override.
    if path:
        out = Path(path)
    else:
        from sustech_survival._cache import config_root
        out = config_root() / "profile.md"
    out = out.expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    return str(out)


__all__ = ["fetch_profile", "gen_usr_profile", "_BLANK_MD"]
